"""update UploadDataModelwithTrack

Revision ID: 02bfb2d05662
Revises: 559390991c39
Create Date: 2022-06-15 23:17:26.937578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02bfb2d05662'
down_revision = '559390991c39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('track_data', sa.Column('track', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('track_data', 'track')
    # ### end Alembic commands ###
